{% set name = "djangorestframework-camel-case" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/djangorestframework-camel-case-{{ version }}.tar.gz
  sha256: cdae75846648abb6585c7470639a1d2fb064dc45f8e8b62aaa50be7f1a7a61f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - djangorestframework_camel_case
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vbabiy/djangorestframework-camel-case
  summary: Camel case JSON support for Django REST framework.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - alexpilot11
